-- 한줄 주석
/*범위주석*/

-- SQL 한 줄 실행 : ctrl + Enter => 4줄 다 한번씩 눌러줌

/* SYS 관리자 계정으로 수행하는 SQL */
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER KH_PHJ IDENTIFIED BY KH1234;

GRANT RESOURCE, CONNECT TO KH_PHJ;

ALTER USER KH_PHJ DEFA ULT TABLESPACE USERS QUOTA 20M ON USERS;