--  체팅회원
CREATE TABLE CAHTMEMBER(
		MEMBER_NO NUMBER CONSTRAINT MEMBER_NO_PK PRIMARY KEY,
		MEMBER_NICKNAME VARCHAR2(50) NOT NULL,
		MEMBER_PASSWORD NVARCHAR2(50) NOT NULL,
		REG_DATE DATE DEFAULT CURRENT_DATE
);

COMMENT ON COLUMN CAHTMEMBER.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN CAHTMEMBER.MEMBER_NICKNAME IS '닉네임';
COMMENT ON COLUMN CAHTMEMBER.MEMBER_PASSWORD IS '비밀번호';
COMMENT ON COLUMN CAHTMEMBER.REG_DATE IS '가입일자';

CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

--셈플추가
INSERT INTO CAHTMEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL, '첫째돼지', '1', DEFAULT);
INSERT INTO CAHTMEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL, '둘리', '1', DEFAULT);

SELECT * FROM CAHTMEMBER;
COMMIT;

DROP TABLE CAHTMEMBER;
DROP SEQUENCE SEQ_MEMBER_NO;

-- 챗팅팅팅
CREATE TABLE CHAT_COMMON(
		CHAT_NO NUMBER CONSTRAINT CHAT_NO_PK PRIMARY KEY,
		MEMBER_NO NUMBER,
		CHAT_BODY NVARCHAR2(2000) NOT NULL,
		CREATION_DATE DATE DEFAULT CURRENT_DATE,
		CONSTRAINT MEMBER_NO_FK FOREIGN KEY (MEMBER_NO)
		REFERENCES CAHTMEMBER (MEMBER_NO) ON DELETE CASCADE
);

COMMENT ON COLUMN CHAT_COMMON.CHAT_NO IS '회원 번호';
COMMENT ON COLUMN CHAT_COMMON.MEMBER_NO IS '작성자';
COMMENT ON COLUMN CHAT_COMMON.CHAT_BODY IS '작성내용';
COMMENT ON COLUMN CHAT_COMMON.CREATION_DATE IS '생성일자';

CREATE SEQUENCE SEQ_CHAT_NO NOCACHE;

-- 셈플추가
-- INSERT INTO CHAT_COMMON VALUES(SEQ_CHAT_NO.NEXTVAL, #{}, #{}, DEFAULT);

SELECT * FROM CHAT_COMMON;
COMMIT;

DROP TABLE CHAT_COMMON;
DROP SEQUENCE SEQ_CHAT_NO;
SELECT
	CHAT_NO,
	MEMBER_NO,
	CHAT_BODY,
	TO_CHAR(CREATION_DATE, 'YYMMDD')
FROM
	CHAT_COMMON;

----------------------
		SELECT
			MEMBER_NICKNAME
		FROM
			CAHTMEMBER
		WHERE
			MEMBER_NO = 1;

