CREATE TABLE MEMBERS(
MEMBER_ID VARCHAR2(20),
MEMBER_PWD VARCHAR2(20) NOT NULL,
MEMBER_NAME CHAR(30),
MEMBER_AGE NUMBER,
MEMBER_EMAIL VARCHAR2(50),
PRIMARY KEY(MEMBER_ID)
);

CREATE TABLE BOARDS(
BOARD_NO NUMBER PRIMARY KEY,
BOARD_TITLE VARCHAR2(100),
BOARD_CONTENT VARCHAR2(4000),
BOARD_WRITER VARCHAR2(20) FOREIGN KEY MEMBERS(MEMBER_ID),
BOARD_REG_DATE DATE DEFAULT '2023-03-22'
);

-------------------------------------------------------
-- ** 수정 ** --
CREATE TABLE MEMBERS(
MEMBER_ID VARCHAR2(20),
MEMBER_PWD VARCHAR2(20) NOT NULL,
MEMBER_NAME VARCHAR(30),
MEMBER_AGE NUMBER,
MEMBER_EMAIL VARCHAR2(50),
PRIMARY KEY(MEMBER_ID)
);

CREATE TABLE BOARDS(
BOARD_NO NUMBER PRIMARY KEY,
BOARD_TITLE VARCHAR2(100),
BOARD_CONTENT VARCHAR2(4000),
BOARD_WRITER VARCHAR2(20) REFERENCES MEMBERS(MEMBER_ID),
BOARD_REG_DATE DATE DEFAULT CURRENT_DATE
);

COMMIT;
INSERT INTO MEMBERS
VALUES ('ID01', 'PASS01', 'USER01', 20, 'USER01@KH.CO');
INSERT INTO MEMBERS
VALUES ('ID02', 'PASS02', 'USER02', 21, 'USER02@KH.CO');
INSERT INTO MEMBERS
VALUES ('ID03', 'PASS03', 'USER03', 22, 'USER03@KH.CO');
INSERT INTO MEMBERS
VALUES ('ID04', 'PASS04', 'USER04', 23, 'USER04@KH.CO');
INSERT INTO MEMBERS
VALUES ('ID05', 'PASS05', 'USER05', 24, 'USER05@KH.CO');
INSERT INTO MEMBERS
VALUES ('ID06', 'PASS06', 'USER06', 25, 'USER06@KH.CO');


SELECT * FROM MEMBERS;

INSERT INTO BOARDS
VALUES ('001', 'BOARD01', 'CONTENT01', 'ID01', DEFAULT);

SELECT * FROM BOARDS;
DROP TABLE BOARDS;
-- PK 확인용1
INSERT INTO MEMBERS
VALUES ('ID01', 'PASS01', 'USER01', 20, 'USER01@KH.CO');
-- PK확인용2
INSERT INTO BOARDS
VALUES ('001', 'BOARD01', 'CONTENT01', 'ID01', DEFAULT);
INSERT INTO BOARDS
VALUES ('002', 'BOARD01', 'CONTENT01', 'ID01', DEFAULT);

-- FK 확인용
INSERT INTO BOARDS
VALUES ('003', 'BOARD01', 'CONTENT01', 'ID02', DEFAULT);
-- FK 오류 발생

-- MEMBERS에 FK 생성후 제확인
INSERT INTO MEMBERS
VALUES ('ID02', 'PASS02', 'USER02', 20, 'USER02@KH.CO');
INSERT INTO BOARDS
VALUES ('003', 'BOARD01', 'CONTENT01', 'ID02', DEFAULT);

SELECT * FROM MEMBERS;
SELECT * FROM BOARDS;

DROP TABLE BOARDS;

CREATE TABLE BOARDS(
BOARD_NO NUMBER PRIMARY KEY,
BOARD_TITLE VARCHAR2(100),
BOARD_CONTENT VARCHAR2(4000),
BOARD_WRITER VARCHAR2(20),
BOARD_REG_DATE DATE DEFAULT CURRENT_DATE,
CONSTRAINT FK_BOARD_WRITER FOREIGN KEY (BOARD_WRITER)
REFERENCES MEMBERS(MEMBER_ID)
);

DROP TABLE MEMBERS;
DROP TABLE BOARDS;
COMMIT;