-- TODOLIST 테이블 생성
CREATE TABLE TODOLIST(
		LIST_NO NUMBER CONSTRAINT LIST_NO_PK PRIMARY KEY,
		TODO_TITLE VARCHAR2(50) NOT NULL,
		TODO_DETAIL NVARCHAR2(1000) NOT NULL,
		COMPLETE CHAR(1) DEFAULT 'X',
		REG_DATE DATE DEFAULT CURRENT_DATE,
		CONSTRAINT COMPLETE_CH CHECK(COMPLETE IN ('O', 'X'))
);

COMMENT ON COLUMN TODOLIST.LIST_NO IS '리스트 번호';
COMMENT ON COLUMN TODOLIST.TODO_TITLE IS '할 일 제목';
COMMENT ON COLUMN TODOLIST.TODO_DETAIL IS '할 일 내용';
COMMENT ON COLUMN TODOLIST.COMPLETE IS '완료여부';
COMMENT ON COLUMN TODOLIST.REG_DATE IS '작성일자';

CREATE SEQUENCE SEQ_LIST_NO NOCACHE;

-- 데이터 생성
INSERT INTO TODOLIST VALUES(SEQ_LIST_NO.NEXTVAL, 'Servlet 공부', '수업 내용 복습-Servlet', DEFAULT, DEFAULT);
INSERT INTO TODOLIST VALUES(SEQ_LIST_NO.NEXTVAL, 'JSP 공부', '수업 내용 복습-JSP', DEFAULT, DEFAULT);

-- 표 확인
SELECT * FROM TODOLIST;

SELECT
	COUNT(COMPLETE)
FROM TODOLIST
WHERE COMPLETE = 'O';

COMMIT;
ROLLBACK;

UPDATE TODOLIST
SET COMPLETE = 'O'
WHERE LIST_NO = 6;

ALTER TABLE TODOLIST
ADD(COLOR VARCHAR2(18));

ALTER TABLE TODOLIST
MODIFY COLOR DEFAULT '#000000';

UPDATE TODOLIST
SET COLOR = '#000000';


----------------------------------------------------------------

-- SUBJECTLIST 테이블 생성
CREATE TABLE SUBJECTLIST(
		SUBJECT_NO NUMBER CONSTRAINT SUBJECT_NO_PK PRIMARY KEY,
		LIST_NO NUMBER,
		SUBJECT_TITLE VARCHAR2(50) CONSTRAINT SUBJECT_TITLE_NN NOT NULL,
		SUBJECT_DETAIL NVARCHAR2(1000),
		COMPLETE CHAR(1) DEFAULT 'X',
		CONSTRAINT SUB_COMPLETE_CH CHECK(COMPLETE IN ('O', 'X')),
		CONSTRAINT LIST_TO_SUBJECT_FK FOREIGN KEY (LIST_NO)
		REFERENCES TODOLIST (LIST_NO) ON DELETE CASCADE
);

COMMENT ON COLUMN SUBJECTLIST.SUBJECT_NO IS '과제 번호';
COMMENT ON COLUMN SUBJECTLIST.LIST_NO IS 'TODOLOST에 해당 되는 할 일 PK';
COMMENT ON COLUMN SUBJECTLIST.SUBJECT_TITLE IS '과제 이름';
COMMENT ON COLUMN SUBJECTLIST.SUBJECT_DETAIL IS '과제 세부내용';
COMMENT ON COLUMN SUBJECTLIST.COMPLETE IS '완료여부';

CREATE SEQUENCE SEQ_SUBJECT_NO NOCACHE;

INSERT INTO SUBJECTLIST VALUES(SEQ_SUBJECT_NO.NEXTVAL, 1, '출석 열심히 하기', '이번수업은 16일이라 빠지면 힘들어요', DEFAULT);

-- 표 확인
SELECT * FROM SUBJECTLIST;

COMMIT;

SELECT
	SUBJECT_NO,
	LIST_NO,
	SUBJECT_TITLE,
	SUBJECT_DETAIL,
	COMPLETE
FROM SUBJECTLIST
ORDER BY SUBJECT_NO;



