-- TODOLIST 테이블 생성
CREATE TABLE TB_TODO(
		TODO_NO NUMBER CONSTRAINT LIST_NO_PK PRIMARY KEY,
		TODO_TITLE VARCHAR2(50) NOT NULL,
		TODO_DETAIL NVARCHAR2(1000) NOT NULL,
		TODO_COMPLETE CHAR(1) DEFAULT '0',
		REG_DATE DATE DEFAULT CURRENT_DATE,
		CONSTRAINT COMPLETE_CH CHECK(TODO_COMPLETE IN ('1', '0'))
);

COMMENT ON COLUMN TB_TODO.TODO_NO IS '리스트 번호';
COMMENT ON COLUMN TB_TODO.TODO_TITLE IS '할 일 제목';
COMMENT ON COLUMN TB_TODO.TODO_DETAIL IS '할 일 내용';
COMMENT ON COLUMN TB_TODO.TODO_COMPLETE IS '완료여부';
COMMENT ON COLUMN TB_TODO.REG_DATE IS '작성일자';

CREATE SEQUENCE SEQ_TODO_NO NOCACHE;

-- 데이터 생성
INSERT INTO TB_TODO VALUES(SEQ_TODO_NO.NEXTVAL, 'Servlet 공부', '수업 내용 복습-Servlet', DEFAULT, DEFAULT);
INSERT INTO TB_TODO VALUES(SEQ_TODO_NO.NEXTVAL, 'JSP 공부', '수업 내용 복습-JSP', DEFAULT, DEFAULT);

-- 표 확인
SELECT * FROM TB_TODO;

DROP TABLE TB_TODO;
DROP SEQUENCE SEQ_TODO_NO;

SELECT
	COUNT(TODO_COMPLETE)
FROM TB_TODO
WHERE TODO_COMPLETE = 'O';

COMMIT;
ROLLBACK;

UPDATE TB_TODO
SET TODO_COMPLETE = 'O'
WHERE TODO_NO = 6;


----------------------------------------------------------------

-- SUBJECTLIST 테이블 생성
CREATE TABLE SUBJECTLIST(
		SUBJECT_NO NUMBER CONSTRAINT SUBJECT_NO_PK PRIMARY KEY,
		LIST_NO NUMBER,
		SUBJECT_TITLE VARCHAR2(50) CONSTRAINT SUBJECT_TITLE_NN NOT NULL,
		SUBJECT_DETAIL NVARCHAR2(1000),
		COMPLETE CHAR(1) DEFAULT 'X',
		CONSTRAINT SUB_COMPLETE_CH CHECK(COMPLETE IN ('O', 'X')),
		CONSTRAINT LIST_TO_SUBJECT_FK FOREIGN KEY (LIST_NO)
		REFERENCES TODOLIST (LIST_NO) ON DELETE CASCADE
);

COMMENT ON COLUMN SUBJECTLIST.SUBJECT_NO IS '과제 번호';
COMMENT ON COLUMN SUBJECTLIST.LIST_NO IS 'TODOLOST에 해당 되는 할 일 PK';
COMMENT ON COLUMN SUBJECTLIST.SUBJECT_TITLE IS '과제 이름';
COMMENT ON COLUMN SUBJECTLIST.SUBJECT_DETAIL IS '과제 세부내용';
COMMENT ON COLUMN SUBJECTLIST.COMPLETE IS '완료여부';

CREATE SEQUENCE SEQ_SUBJECT_NO NOCACHE;

INSERT INTO SUBJECTLIST VALUES(SEQ_SUBJECT_NO.NEXTVAL, 1, '출석 열심히 하기', '이번수업은 16일이라 빠지면 힘들어요', DEFAULT);

-- 표 확인
SELECT * FROM SUBJECTLIST;

COMMIT;

SELECT
	SUBJECT_NO,
	LIST_NO,
	SUBJECT_TITLE,
	SUBJECT_DETAIL,
	COMPLETE
FROM SUBJECTLIST
ORDER BY SUBJECT_NO;



