CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_NAME"	NVARCHAR2(5)		NOT NULL,
	"MEMBER_ID"	NVARCHAR2(12)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(4000)		NOT NULL,
	"MEMBER_EMAIL"	NVARCHAR2(50)		NOT NULL,
	"MEMBER_PHONE"	NVARCHAR2(11)		NOT NULL,
	"ARTIST_REG"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_PENALTY"	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '회원이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원이메일';

COMMENT ON COLUMN "MEMBER"."MEMBER_PHONE" IS '회원전화번호';

COMMENT ON COLUMN "MEMBER"."ARTIST_REG" IS '직가등록여부(N,Y)';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '회원탈퇴여부(N,Y)';

COMMENT ON COLUMN "MEMBER"."MEMBER_PENALTY" IS '회원패널티(1,2)';

CREATE TABLE "ARTIST" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"ARTIST_PROFILE"	NVARCHAR2(200)		NOT NULL,
	"ARTIST_NICKNAME"	NVARCHAR2(12)		NOT NULL,
	"ARTIST_PORTFOLIO"	NVARCHAR2(200)		NOT NULL,
	"ARTIST_BANK_NAME"	VARCHAR(20)		NOT NULL,
	"ARTIST_BANK_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "ARTIST"."MEMBER_NO" IS '작가 회원번호';

COMMENT ON COLUMN "ARTIST"."ARTIST_PROFILE" IS '작가프로필 파일명';

COMMENT ON COLUMN "ARTIST"."ARTIST_NICKNAME" IS '작가 활동명';

COMMENT ON COLUMN "ARTIST"."ARTIST_PORTFOLIO" IS '포트폴리오파일명';

COMMENT ON COLUMN "ARTIST"."ARTIST_BANK_NAME" IS '환전 은행명';

COMMENT ON COLUMN "ARTIST"."ARTIST_BANK_NO" IS '환전 은행번호';

CREATE TABLE "PIECE" (
	"PIECE_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"PIECE_RENAME"	NVARCHAR2(200)		NOT NULL,
	"PIECE_TITLE"	NVARCHAR2(200)		NOT NULL,
	"PIECE_DETAIL"	NVARCHAR2(1000)		NOT NULL,
	"SIZE_X"	NUMBER	DEFAULT 0	NOT NULL,
	"SIZE_Y"	NUMBER	DEFAULT 0	NOT NULL,
	"REG_DATE"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"PIECE_TYPE"	NUMBER		NOT NULL,
	"PIECE_STATUS"	CHAR(1)		NOT NULL,
	"PIECE_CATEGORY_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PIECE"."PIECE_NO" IS '작품번호(SEQ_PIECE_NO)';

COMMENT ON COLUMN "PIECE"."MEMBER_NO" IS '작가 회원번호';

COMMENT ON COLUMN "PIECE"."PIECE_RENAME" IS '작품 파일명';

COMMENT ON COLUMN "PIECE"."PIECE_TITLE" IS '작품 제목';

COMMENT ON COLUMN "PIECE"."PIECE_DETAIL" IS '작품 설명';

COMMENT ON COLUMN "PIECE"."SIZE_X" IS '작품크기(가로)';

COMMENT ON COLUMN "PIECE"."SIZE_Y" IS '작품크기(세로)';

COMMENT ON COLUMN "PIECE"."REG_DATE" IS '등록일';

COMMENT ON COLUMN "PIECE"."PIECE_TYPE" IS '판매종류(1 즉시판매, 2 경매)';

COMMENT ON COLUMN "PIECE"."PIECE_STATUS" IS '상태';

COMMENT ON COLUMN "PIECE"."PIECE_CATEGORY_NO" IS '카테고리번호(SEQ_CATEGORY_NO)';

CREATE TABLE "AUCTION" (
	"AUCTION"	NUMBER		NOT NULL,
	"PIECE_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BID_DATE"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"END_PRICE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "AUCTION"."AUCTION" IS '입찰번호(SEQ_AUCTION_NO)';

COMMENT ON COLUMN "AUCTION"."PIECE_NO" IS '작품번호';

COMMENT ON COLUMN "AUCTION"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "AUCTION"."BID_DATE" IS '입찰시간';

COMMENT ON COLUMN "AUCTION"."END_PRICE" IS '경매가';

CREATE TABLE "NOTIFICATION" (
	"NOTI_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"READ_CHECK"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"NOTI_CONTENT"	NVARCHAR2(1000)		NOT NULL
);

COMMENT ON COLUMN "NOTIFICATION"."NOTI_NO" IS '알림번호 (SEQ_NOTI_NO)';

COMMENT ON COLUMN "NOTIFICATION"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "NOTIFICATION"."READ_CHECK" IS '알림 읽음여부';

COMMENT ON COLUMN "NOTIFICATION"."NOTI_CONTENT" IS '알림내용';

CREATE TABLE "DELIVERY" (
	"DELIVERY_NO"	VARCHAR2(50)		NOT NULL,
	"PIECE_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"DELIVERY_ADDRESS"	VARCHAR2(200)		NOT NULL,
	"DELIVERY_STATUS"	NUMBER		NOT NULL,
	"DELIVERY_DATE"	DATE	DEFAULT CURRENT_DATE	NOT NULL
);

COMMENT ON COLUMN "DELIVERY"."DELIVERY_NO" IS '송장번호(SEQ_DELIVERY_NO)';

COMMENT ON COLUMN "DELIVERY"."PIECE_NO" IS '작품번호(SEQ_PIECE_NO)';

COMMENT ON COLUMN "DELIVERY"."MEMBER_NO" IS '수취인';

COMMENT ON COLUMN "DELIVERY"."DELIVERY_ADDRESS" IS '배송지 주소';

COMMENT ON COLUMN "DELIVERY"."DELIVERY_STATUS" IS '배송상태';

COMMENT ON COLUMN "DELIVERY"."DELIVERY_DATE" IS '배송등록일';

CREATE TABLE "FOLLOW" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_NO2"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "FOLLOW"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "FOLLOW"."MEMBER_NO2" IS '작가 회원번호';

CREATE TABLE "WISH" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"PIECE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "WISH"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "WISH"."PIECE_NO" IS '찜 한 작품번호';

CREATE TABLE "PAYMENT_RECORD" (
	"RECORD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"PAY_AMOUNT"	NUMBER		NOT NULL,
	"PAY_DATE"	NUMBER		NOT NULL,
	"PAY_TYPE"	NVARCHAR2(50)		NOT NULL,
	"PAY_CODE"	NUMBER		NOT NULL,
	"PIECE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PAYMENT_RECORD"."RECORD_NO" IS '결제번호';

COMMENT ON COLUMN "PAYMENT_RECORD"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "PAYMENT_RECORD"."PAY_AMOUNT" IS '결제금액';

COMMENT ON COLUMN "PAYMENT_RECORD"."PAY_DATE" IS '결제일자';

COMMENT ON COLUMN "PAYMENT_RECORD"."PAY_TYPE" IS '결제수단';

COMMENT ON COLUMN "PAYMENT_RECORD"."PAY_CODE" IS '결제수단번호';

COMMENT ON COLUMN "PAYMENT_RECORD"."PIECE_NO" IS '결제한 작품번호';

CREATE TABLE "REPORT" (
	"REPORT_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"PIECE_NO"	NUMBER		NOT NULL,
	"REPORT_TYPE"	NUMBER		NOT NULL,
	"REPORT_CONTENT"	NVARCHAR2(1000)		NOT NULL,
	"REPORT_DATE"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"REPORT_READ_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"REPORT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "REPORT"."REPORT_NO" IS '신고번호(SEQ_REPORT_NO)';

COMMENT ON COLUMN "REPORT"."MEMBER_NO" IS '신고자번호';

COMMENT ON COLUMN "REPORT"."PIECE_NO" IS '작품번호';

COMMENT ON COLUMN "REPORT"."REPORT_TYPE" IS '신고사유';

COMMENT ON COLUMN "REPORT"."REPORT_CONTENT" IS '신고내용';

COMMENT ON COLUMN "REPORT"."REPORT_DATE" IS '신고날자';

COMMENT ON COLUMN "REPORT"."REPORT_READ_FL" IS '읽음여부(N, Y)';

COMMENT ON COLUMN "REPORT"."REPORT_DEL_FL" IS '삭제여부(N, Y)';

CREATE TABLE "QUESTION" (
	"QUESTION_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"QUESTION_CONTENT"	NVARCHAR2(1000)		NOT NULL,
	"QUESTION_DATE"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"QUESTION_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"QUESTION_ANS_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"QUESTION_ANSWER"	NVARCHAR2(1000)		NULL,
	"QUESTION_CATEGORY_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "QUESTION"."QUESTION_NO" IS '문의번호(SEQ_QUESTION_NO)';

COMMENT ON COLUMN "QUESTION"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "QUESTION"."QUESTION_CONTENT" IS '문의내용';

COMMENT ON COLUMN "QUESTION"."QUESTION_DATE" IS '문의날자';

COMMENT ON COLUMN "QUESTION"."QUESTION_DEL_FL" IS '삭제여부 (N, Y)';

COMMENT ON COLUMN "QUESTION"."QUESTION_ANS_FL" IS '답변여부 (N, Y)';

COMMENT ON COLUMN "QUESTION"."QUESTION_ANSWER" IS '답변내용';

COMMENT ON COLUMN "QUESTION"."QUESTION_CATEGORY_NO" IS '분류번호(SEQ_QUESTION_CATEGORY_NO)';

CREATE TABLE "PIECE_AUCTION" (
	"PIECE_NO"	NUMBER		NOT NULL,
	"START_DATE"	DATE		NOT NULL,
	"END_DATE"	DATE		NOT NULL,
	"START_PRICE"	NUMBER		NOT NULL,
	"HOPE_PRICE"	NUMBER		NOT NULL,
	"FINAL_PRICE"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "PIECE_AUCTION"."PIECE_NO" IS '작품번호';

COMMENT ON COLUMN "PIECE_AUCTION"."START_DATE" IS '경매 시작 시간';

COMMENT ON COLUMN "PIECE_AUCTION"."END_DATE" IS '경매종료 시간';

COMMENT ON COLUMN "PIECE_AUCTION"."START_PRICE" IS '경매 시작가';

COMMENT ON COLUMN "PIECE_AUCTION"."HOPE_PRICE" IS '상한낙찰가';

COMMENT ON COLUMN "PIECE_AUCTION"."FINAL_PRICE" IS '최종낙찰가';

CREATE TABLE "NOTICE" (
	"NOTICE_NO"	NUMBER		NOT NULL,
	"NOTICE_TITLE"	NVARCHAR2(50)		NOT NULL,
	"NOTICE_CONTENT"	NVARCHAR2(1000)		NOT NULL,
	"NOTICE_DATE"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"NOTICE_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS '공지사항글번호(SEQ_NOTICE_NO)';

COMMENT ON COLUMN "NOTICE"."NOTICE_TITLE" IS '공지글제목';

COMMENT ON COLUMN "NOTICE"."NOTICE_CONTENT" IS '공지글내용';

COMMENT ON COLUMN "NOTICE"."NOTICE_DATE" IS '작성일';

COMMENT ON COLUMN "NOTICE"."NOTICE_DEL_FL" IS '상태(N 작성, T 임시보관,D 삭제,)';


CREATE TABLE "PIECE_CATEGORY" (
	"PIECE_CATEGORY_NO"	NUMBER		NOT NULL,
	"PIECE_CATEGORY_NAME"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "PIECE_CATEGORY"."PIECE_CATEGORY_NO" IS '카테고리번호(SEQ_CATEGORY_NO)';

COMMENT ON COLUMN "PIECE_CATEGORY"."PIECE_CATEGORY_NAME" IS '카테고리 이름';

CREATE TABLE "QUESTION_CATEGORY" (
	"QUESTION_CATEGORY_NO"	NUMBER		NOT NULL,
	"QUESTION_CATEGORY_NAME"	NVARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "QUESTION_CATEGORY"."QUESTION_CATEGORY_NO" IS '분류번호(SEQ_QUESTION_CATEGORY_NO)';

COMMENT ON COLUMN "QUESTION_CATEGORY"."QUESTION_CATEGORY_NAME" IS '문의종류';

CREATE TABLE "PIECE_SELL" (
	"PIECE_NO"	NUMBER		NOT NULL,
	"SELL_PRICE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PIECE_SELL"."PIECE_NO" IS '작품번호';

COMMENT ON COLUMN "PIECE_SELL"."SELL_PRICE" IS '판매가격';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "ARTIST" ADD CONSTRAINT "PK_ARTIST" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "PIECE" ADD CONSTRAINT "PK_PIECE" PRIMARY KEY (
	"PIECE_NO"
);

ALTER TABLE "AUCTION" ADD CONSTRAINT "PK_AUCTION" PRIMARY KEY (
	"AUCTION"
);

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY (
	"NOTI_NO"
);

ALTER TABLE "DELIVERY" ADD CONSTRAINT "PK_DELIVERY" PRIMARY KEY (
	"DELIVERY_NO"
);

ALTER TABLE "FOLLOW" ADD CONSTRAINT "PK_FOLLOW" PRIMARY KEY (
	"MEMBER_NO",
	"MEMBER_NO2"
);

ALTER TABLE "WISH" ADD CONSTRAINT "PK_WISH" PRIMARY KEY (
	"MEMBER_NO",
	"PIECE_NO"
);

ALTER TABLE "PAYMENT_RECORD" ADD CONSTRAINT "PK_PAYMENT_RECORD" PRIMARY KEY (
	"RECORD_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"REPORT_NO"
);

ALTER TABLE "QUESTION" ADD CONSTRAINT "PK_QUESTION" PRIMARY KEY (
	"QUESTION_NO"
);

ALTER TABLE "PIECE_AUCTION" ADD CONSTRAINT "PK_PIECE_AUCTION" PRIMARY KEY (
	"PIECE_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_NO"
);

ALTER TABLE "PIECE_CATEGORY" ADD CONSTRAINT "PK_PIECE_CATEGORY" PRIMARY KEY (
	"PIECE_CATEGORY_NO"
);

ALTER TABLE "QUESTION_CATEGORY" ADD CONSTRAINT "PK_QUESTION_CATEGORY" PRIMARY KEY (
	"QUESTION_CATEGORY_NO"
);

ALTER TABLE "PIECE_SELL" ADD CONSTRAINT "PK_PIECE_SELL" PRIMARY KEY (
	"PIECE_NO"
);

ALTER TABLE "ARTIST" ADD CONSTRAINT "FK_MEMBER_TO_ARTIST_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "PIECE" ADD CONSTRAINT "FK_ARTIST_TO_PIECE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "ARTIST" (
	"MEMBER_NO"
);

ALTER TABLE "PIECE" ADD CONSTRAINT "FK_PIECE_CATEGORY_TO_PIECE_1" FOREIGN KEY (
	"PIECE_CATEGORY_NO"
)
REFERENCES "PIECE_CATEGORY" (
	"PIECE_CATEGORY_NO"
);

ALTER TABLE "AUCTION" ADD CONSTRAINT "FK_PIECE_TO_AUCTION_1" FOREIGN KEY (
	"PIECE_NO"
)
REFERENCES "PIECE" (
	"PIECE_NO"
);

ALTER TABLE "AUCTION" ADD CONSTRAINT "FK_MEMBER_TO_AUCTION_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_NOTIFICATION_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "DELIVERY" ADD CONSTRAINT "FK_PIECE_TO_DELIVERY_1" FOREIGN KEY (
	"PIECE_NO"
)
REFERENCES "PIECE" (
	"PIECE_NO"
);

ALTER TABLE "DELIVERY" ADD CONSTRAINT "FK_MEMBER_TO_DELIVERY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "FOLLOW" ADD CONSTRAINT "FK_MEMBER_TO_FOLLOW_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "FOLLOW" ADD CONSTRAINT "FK_ARTIST_TO_FOLLOW_1" FOREIGN KEY (
	"MEMBER_NO2"
)
REFERENCES "ARTIST" (
	"MEMBER_NO"
);

ALTER TABLE "WISH" ADD CONSTRAINT "FK_MEMBER_TO_WISH_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "WISH" ADD CONSTRAINT "FK_PIECE_TO_WISH_1" FOREIGN KEY (
	"PIECE_NO"
)
REFERENCES "PIECE" (
	"PIECE_NO"
);

ALTER TABLE "PAYMENT_RECORD" ADD CONSTRAINT "FK_MEMBER_TO_PAYMENT_RECORD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "PAYMENT_RECORD" ADD CONSTRAINT "FK_PIECE_TO_PAYMENT_RECORD_1" FOREIGN KEY (
	"PIECE_NO"
)
REFERENCES "PIECE" (
	"PIECE_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_PIECE_TO_REPORT_1" FOREIGN KEY (
	"PIECE_NO"
)
REFERENCES "PIECE" (
	"PIECE_NO"
);

ALTER TABLE "QUESTION" ADD CONSTRAINT "FK_MEMBER_TO_QUESTION_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "QUESTION" ADD CONSTRAINT "FK_QUESTION_CATEGORY_TO_QUESTION_1" FOREIGN KEY (
	"QUESTION_CATEGORY_NO"
)
REFERENCES "QUESTION_CATEGORY" (
	"QUESTION_CATEGORY_NO"
);

ALTER TABLE "PIECE_AUCTION" ADD CONSTRAINT "FK_PIECE_TO_PIECE_AUCTION_1" FOREIGN KEY (
	"PIECE_NO"
)
REFERENCES "PIECE" (
	"PIECE_NO"
);

ALTER TABLE "PIECE_SELL" ADD CONSTRAINT "FK_PIECE_TO_PIECE_SELL_1" FOREIGN KEY (
	"PIECE_NO"
)
REFERENCES "PIECE" (
	"PIECE_NO"
);


------------------------------------------------------------------------------
------------------------------------------------------------------------------

-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;
CREATE SEQUENCE SEQ_PIECE_NO NOCACHE;
CREATE SEQUENCE SEQ_AUCTION_NO NOCACHE;
CREATE SEQUENCE SEQ_CATEGORY_NO NOCACHE;
CREATE SEQUENCE SEQ_NOTI_NO NOCACHE;
CREATE SEQUENCE SEQ_DELIVERY_NO NOCACHE;
CREATE SEQUENCE SEQ_REPORT_NO NOCACHE;
CREATE SEQUENCE SEQ_QUESTION_NO NOCACHE;
CREATE SEQUENCE SEQ_QUESTION_CATEGORY_NO NOCACHE;
CREATE SEQUENCE SEQ_NOTICE_NO NOCACHE;

DROP SEQUENCE SEQ_MEMBER_NO;
DROP SEQUENCE SEQ_PIECE_NO;
DROP SEQUENCE SEQ_AUCTION_NO;
DROP SEQUENCE SEQ_CATEGORY_NO;
DROP SEQUENCE SEQ_NOTI_NO;
DROP SEQUENCE SEQ_DELIVERY_NO;
DROP SEQUENCE SEQ_REPORT_NO;
DROP SEQUENCE SEQ_QUESTION_NO;
DROP SEQUENCE SEQ_QUESTION_CATEGORY_NO;
DROP SEQUENCE SEQ_NOTICE_NO;




------------------------------------------------------------------------------
------------------------------------------------------------------------------

COMMIT;

-- 맴버 샘플 확인
SELECT * FROM "MEMBER";
